#' Firing Rate and Mean Firing Rate
#'
#' @param object Object of class MEASpikeR generated by the \code{dataset_filtering} function
#' @param filt.data.path Path to "MEA_DATA2ANALYZE.Rdat" file generated by the \code{dataset_filtering} function
#' @param output_directory Character specifying the directory where we want to save the output excel file
#'
#' @return An excel file with the firing rate and the mean firing rate for each condition located in the output directory
#' specified in the \code{output_directory} argument
#' @export
#' @author François-Xavier Lejeune, Gaspard Martet, Carine Dalle
#' @references Dalle C., Martet G., Kaddouri Y., Rebola N., Whitmarsh S., Lejeune FX.(2023). **_MEASpikeR_: a new package
#' for spike analysis and visualization of _in vitro_ MEA data**.
#'
#' @examples \dontrun{
#' out.MEA <- MEASpikeR::dataset_filtering(data.path = "C:/Users/prenom.nom/Documents/data",
#' guideline_name_file = "MEA_Spikes_ANA_R_guideline",
#' save.rDATA = TRUE)
#'
#' # if you want to work with the MEASpikeR object
#' MEASpikeR::firing_rate(
#' object = out.MEA,
#' output_directory = "C:/Users/prenom.nom/Documents"
#' )
#'
#' # if you want to work with the saved Rdat file
#' MEASpikeR::firing_rate(
#' filt.data.path = "C:/Users/prenom.nom/Documents/data/MEA_DATA2ANALYZE.Rdat",
#' output_directory = "C:/Users/prenom.nom/Documents"
#' )}
firing_rate <- function(
    object = NA,
    filt.data.path = NA,
    output_directory = NA
) {

  if ( all(!(is.na(object))) & class(object) == "MEASpikeR") {

    attach(object)

  } else {

    if (!(is.na(filt.data.path))) {

      load(filt.data.path)

    } else {

      stop("arguments object and filt.data.path are missing, with no default.")

    } }

  FR <- NULL

  # working directory

  if(!is.na(output_directory)) {setwd(output_directory)}

  else {stop("argument 'output_directory' is missing with no default")}

  # loop over the conditions of the guideline file

  for (j in 1:nb.condition) {

    #-- Import filtered data --#

    dat.spike <- get(as.character(info.cond$Filename[j]))

    if (nrow(dat.spike) == 0) next

    #--------------------------------------------------------#

    #-- Calculation of the firing rate for each electrode -- #

    #--------------------------------------------------------#

    newFR <- stats::aggregate(dat.spike$channel, list(dat.spike$channel, dat.spike$cluster_id), length)
    colnames(newFR) <- c("channel", "cluster_id", "nb.spike")
    TaN <- info.cond$time.analyzed[j]
    Condition <- info.cond$ConditionNumber[j]

    newFR <- data.frame(ConditionNumber = Condition, newFR, TaN = TaN)
    newFR <- data.frame(newFR, firing_rate = round(newFR$nb.spike/newFR$TaN, 4) )

    #-- if parameter "minFR" is set to zero add channels with FR = 0 --#

    # List of analyzed channels (= all electrodes - removed channels)

    if (length(guideline[ j, "removeChannel" ]) == 0) an.ch <- 1:nb.electrode

    if (length(guideline[ j, "removeChannel" ]) > 0) {

      ix.rm.ch <- unlist(strsplit( guideline[ j, "removeChannel" ], split = ","))
      ix.rm.ch <- as.numeric(ix.rm.ch)
      an.ch <- setdiff(1:nb.electrode, ix.rm.ch)
      an.ch <- sort(unique(an.ch))

    }

    if (info.cond$MinFR[j] == 0) {

      add.ch <- setdiff( an.ch, sort(unique(newFR$channel)) )

      if (length(add.ch) > 0) {

        newFR.add <- data.frame(ConditionNumber = Condition, channel = add.ch, cluster_id = "none",
                                nb.spike = 0, TaN = TaN, firing_rate = 0)

        newFR <- rbind(newFR, newFR.add)

      }

    }

    FR <- rbind(FR, newFR)

  } # end_for_condition

  FR <- merge(FR, info.cond[,c("ConditionNumber", "ShortFilename", "record_duration", "start_TW",
                               "end_TW", "TeX")], by = "ConditionNumber")

  FR <- merge(FR, guideline[,c("ConditionNumber", "ExperimentalCondition", "ExperimentalGroup")], by = "ConditionNumber")

  FR$TimeWindow <- paste(FR$start_TW, FR$end_TW, sep = "-")

  FR <- FR[, c("ConditionNumber", "ShortFilename", "TimeWindow", "record_duration",
               "ExperimentalGroup", "ExperimentalCondition",
               "channel", "cluster_id", "nb.spike", "firing_rate", "TaN", "TeX") ]

  FR <- FR[order(FR$ConditionNumber, FR$channel, FR$cluster_id), ]

  #-------------------------------------------------------------#

  #-- Calculation of the mean firing rate for each condition -- #

  #-------------------------------------------------------------#

  MFR <- FR %>%
    dplyr::group_by(ConditionNumber) %>%
    dplyr::summarise(
      "MeanFiringRate (Hz)" = round(mean(firing_rate), 4),
      SD = round(stats::sd(firing_rate, na.rm = TRUE), 4),
      nb.active.electrodes = length(unique(channel))
    )

  MFR <- merge(MFR, info.cond[,c("ConditionNumber", "ShortFilename", "record_duration", "start_TW",
                                 "end_TW", "nb.ch.excluded", "time.analyzed", "TeX")], by = "ConditionNumber", all.y = TRUE)

  MFR <- merge(MFR, guideline[,c("ConditionNumber", "ExperimentalCondition", "ExperimentalGroup")],
               by = "ConditionNumber", all.y = TRUE)

  MFR$TimeWindow <- paste(MFR$start_TW, MFR$end_TW, sep = "-")
  MFR$`%active.electrodes` <- round(MFR$nb.active.electrodes/(nb.electrode-MFR$nb.ch.excluded)*100, 1)

  MFR <- MFR[, c("ConditionNumber", "ShortFilename", "TimeWindow", "record_duration",
                 "ExperimentalGroup", "ExperimentalCondition",
                 "MeanFiringRate (Hz)", "SD",
                 "nb.active.electrodes", "nb.ch.excluded", "%active.electrodes",
                 "TeX", "time.analyzed") ]
  colnames(MFR)[ colnames(MFR) == "time.analyzed" ] <- "TaN"

  #-- Name of output file --#

  info <- guideline$InformationFolderName[1]

  systime <- Sys.time()
  systime <- paste0(systime, "s")
  systime <- gsub(" ", "_", systime)
  ix <- unlist(gregexpr("\\:", systime))
  substr(systime, ix[1], ix[1]) <- "h"
  substr(systime, ix[2], ix[2]) <- "m"

  output.file <- paste0("FR&MFR_", systime)

  if (MinFR > 0) { output.file <- paste0(output.file, "_MinFR", MinFR) }

  if (!(is.na(info))) output.file <- paste0(output.file, "_", info)

  output.file <- paste0(output.file, ".xlsx")

  #-- Save FR, MFR and guideline (guideline) on excel file --#

  x <- list(
    FiringRate = FR,
    MFR = MFR,
    guideline = guideline
  )

  writexl::write_xlsx(
    x, path = paste(getwd(), output.file, sep = "/"),
    col_names = TRUE, format_headers = TRUE, use_zip64 = FALSE
  )

} # FUNCTION END_MEA_4_EXTRACTION_FR_MFR
