#' Spike Detection Rate
#'
#' @param object Object of class MEASpikeR generated by the \code{dataset_filtering} function
#' @param filt.data.path Path to the ".Rdat" file generated by the \code{dataset_filtering} function
#' @param working_directory Character specifying the working directory where we want to save the output excel file
#' @param spike_col Character specifying the color for the spikes with no spike sorting (by default "forestgreen")
#' @param plot Character specifying the type of plot ("needle" or "line") (by default "line")
#'
#' @return An excel file calles "AWSDR" with date and time as prefix is created with as many sheets as there are conditions,
#' where each sheet contains a table with two columns.
#' The first column indicates time, and the second column indicates the firing rate.
#' Additionally, there is a graphic per condition representing the firing rate (Hz) as a function of time (s).
#' All these files are saved in the working directory specified in the 'working_directory' argument.
#' @export
#' @author François-Xavier Lejeune, Gaspard Martet, Carine Dalle, Stephen Whitmarsh
#'
#' @examples \dontrun{
#' out.MEA <- MEASpikeR::dataset_filtering(data.path = "C:/Users/prenom.nom/Documents/data",
#' guideline_name_file = "MEA_Spikes_ANA_R_guideline",
#' save.rDATA = TRUE)
#'
#' # if you want to work with the MEASpikeR object
#' MEASpikeR::spike_detection_rate(
#' object = out.MEA,
#' working_directory = "C:/Users/prenom.nom/Documents"
#' )
#'
#' # if you want to work with the saved Rdat file
#' MEASpikeR::spike_detection_rate(
#' filt.data.path = "C:/Users/prenom.nom/Documents/data/MEA_DATA2ANALYZE.Rdat",
#' working_directory = "C:/Users/prenom.nom/Documents"
#' )
#' }
spike_detection_rate <- function(
    object = NA,
    filt.data.path = NA,
    working_directory = NA,
    spike_col = "forestgreen",
    plot = "line"
) {

  if ( all(!(is.na(object))) & class(object) == "MEASpikeR") {

    attach(object)

  } else {

    if (!(is.na(filt.data.path))) {

      load(filt.data.path)

    } else {

      stop("arguments object and filt.data.path are missing, with no default.")

    } }

  # working directory

  if(!is.na(working_directory)) {setwd(working_directory)}

  else {stop("argument 'working_directory' is missing with no default")}


  #-- Main --#

  info <- guideline$InformationFolderName[1]

  systime <- Sys.time()
  systime <- paste0(systime, "s")
  systime <- gsub(" ", "_", systime)
  ix <- unlist(gregexpr("\\:", systime))
  substr(systime, ix[1], ix[1]) <- "h"
  substr(systime, ix[2], ix[2]) <- "m"

  output.filename <- paste0("AWSDR_", systime)

  SpikeRate <- list()

  for (i in 1:nb.condition) {

    cat("### condition =", i, "\n")

    start_TW <- guideline$TimeLimitStart[i]
    end_TW <- guideline$TimeLimitEnd[i]

    cond.nb <- guideline$ConditionNumber[i]
    expgrp <- guideline$ExperimentalGroup[i]
    expcond <- guideline$ExperimentalCondition[i]
    TeX <- info.cond$TeX[i]

    spike.sorting  <- info.cond$spike.sorting[i]
    index  <- info.cond$index[i]
    cutoff  <- info.cond$cutoff[i]

    shortname <- info.cond$ShortFilename[i]

    name <- paste0(shortname, "_C_", cond.nb, "_", expgrp, "_", expcond, "\n",
                   "_TW_", start_TW, "-", end_TW, "_TeX_", TeX,
                   "_MinFR_", MinFR)

    if (spike.sorting) name <- paste0(name, "_index_", index, "_", "cutoff", "_", gsub("\\.", "", cutoff))


    # Retrieve filtered dataspike + output filename and title name

    tmp <- get(paste0("filtered.dataspike", info.cond$ConditionNumber[i]))

    spike.time <- tmp$within_session_time_ms/1000
    t <- start_TW:end_TW
    spike.freq <- table(cut(spike.time, breaks = t))
    Time <- seq(start_TW+.5, end_TW-.5, 1)

    df <- data.frame(Time = Time, FR = as.numeric(spike.freq))

    time.range <- end_TW - start_TW
    step <- 100
    if (time.range <= 50) step <- 5
    if (time.range > 50 & time.range <= 100) step <- 10
    if (time.range > 100 & time.range <= 200) step <- 25
    if (time.range > 200 & time.range <= 600) step <- 50

    if (plot == "needle") {

      p <- ggplot2::ggplot(data = df, ggplot2::aes(x = Time, ymax = FR, ymin = 0)) +
        ggplot2::geom_linerange(color = spike_col, linewidth = .3)

    } else {

      p <- ggplot2::ggplot(data = df, ggplot2::aes(x = Time, y = FR)) +
        ggplot2::geom_line(color = spike_col, linewidth = .3)

    }

    p <- p + ggplot2::theme_minimal() +
      ggplot2::xlab("Time (s)") + ggplot2::ylab("Rate (Hz)") +
      ggplot2::ggtitle(name) +
      ggplot2::theme(
        axis.text = ggplot2::element_text(color = "black", size = 8),
        axis.title = ggplot2::element_text(size = 8),
        plot.title = ggplot2::element_text(size = 8)
      ) +
      ggplot2::scale_x_continuous(breaks = seq(start_TW, end_TW, step),
                         expand = c(.01, 0), limits = c(start_TW, end_TW))

    output.filename.tmp <- paste0(output.filename, "_C", cond.nb)
    if(!(is.na(info))) output.filename.tmp <- paste0(output.filename.tmp, "_", info)

    grDevices::tiff(paste0(output.filename.tmp, ".tiff"), width = 2100, height = 1400, res = 400)

    print(p)

    grDevices::dev.off()

    df$Time <- ceiling(df$Time)

    SpikeRate[[i]] <- df

  } # End_For_Condition

  names(SpikeRate) <- info.cond$ConditionNumber

  openxlsx::write.xlsx(SpikeRate, file = paste0(output.filename, ".xlsx"))

} # FUNCTION END_MEA_7_SPIKEDETECTIONRATE
